# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'SimplicITy' do
pod "AFNetworking", "~> 2.0"
pod 'MBProgressHUD', '~> 0.8'
end

target 'SimplicITyTests' do

end

